export CC=clang;
export CXX=clang++; 
mkdir -p ../build; 
cd ../build; 
cmake ../acc-cosc-1337-spring-2021-artgonzalezacc/; 
make;
pwd; 
cd test;
cd classwork_test;
cd 09_assign_test;
./ex_09_tests -s;
